kafka:
  bootstrap:
    servers: localhost:9092
mp:
  messaging:
    outgoing:
      invoices:
        connector: smallrye-kafka
        topic: invoices
        merge: true
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer
quarkus:
  http:
    port: 5001
